/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAppRouteImport } from './routes/admin/_app'
import { Route as KitchenIndexRouteImport } from './routes/kitchen/index'
import { Route as KitchenAppRouteImport } from './routes/kitchen/_app'
import { Route as ReceptionIndexRouteImport } from './routes/reception/index'
import { Route as ReceptionAppRouteImport } from './routes/reception/_app'
import { Route as AdminAppDashboardRouteImport } from './routes/admin/_app.dashboard'
import { Route as AdminAppEmployeesRouteImport } from './routes/admin/_app.employees'
import { Route as AdminAppKdsRouteImport } from './routes/admin/_app.kds'
import { Route as AdminAppOrdersRouteImport } from './routes/admin/_app.orders'
import { Route as AdminAppQrRouteImport } from './routes/admin/_app.qr'
import { Route as AdminMenuTableRouteImport } from './routes/admin/menu.$table'
import { Route as KitchenAppKdsRouteImport } from './routes/kitchen/_app.kds'
import { Route as ReceptionAppCustomersRouteImport } from './routes/reception/_app.customers'
import { Route as ReceptionAppDashboardRouteImport } from './routes/reception/_app.dashboard'
import { Route as ReceptionAppProfileRouteImport } from './routes/reception/_app.profile'
import { Route as AdminAppBillingInvoicesRouteImport } from './routes/admin/_app.billing.invoices'
import { Route as AdminAppBillingPaymentsRouteImport } from './routes/admin/_app.billing.payments'
import { Route as AdminAppInventoryIngredientsRouteImport } from './routes/admin/_app.inventory.ingredients'
import { Route as AdminAppInventoryPurchaseOrdersRouteImport } from './routes/admin/_app.inventory.purchase-orders'
import { Route as AdminAppInventorySuppliersRouteImport } from './routes/admin/_app.inventory.suppliers'
import { Route as AdminAppMenuItemsRouteImport } from './routes/admin/_app.menu.items'
import { Route as KitchenAppMenuAddRouteImport } from './routes/kitchen/_app.menu.add'
import { Route as KitchenAppMenuItemsRouteImport } from './routes/kitchen/_app.menu.items'
import { Route as KitchenAppOrdersHistoryRouteImport } from './routes/kitchen/_app.orders.history'
import { Route as KitchenAppOrdersLiveRouteImport } from './routes/kitchen/_app.orders.live'
import { Route as ReceptionAppBillingPaymentsRouteImport } from './routes/reception/_app.billing.payments'
import { Route as ReceptionAppInventoryIngredientsRouteImport } from './routes/reception/_app.inventory.ingredients'
import { Route as ReceptionAppInventoryPurchaseOrdersRouteImport } from './routes/reception/_app.inventory.purchase-orders'
import { Route as ReceptionAppInventorySuppliersRouteImport } from './routes/reception/_app.inventory.suppliers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppRoute = AdminAppRouteImport.update({
  id: '/admin/_app',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenIndexRoute = KitchenIndexRouteImport.update({
  id: '/kitchen/',
  path: '/kitchen/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenAppRoute = KitchenAppRouteImport.update({
  id: '/kitchen/_app',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionIndexRoute = ReceptionIndexRouteImport.update({
  id: '/reception/',
  path: '/reception/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionAppRoute = ReceptionAppRouteImport.update({
  id: '/reception/_app',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppDashboardRoute = AdminAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppEmployeesRoute = AdminAppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppKdsRoute = AdminAppKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppOrdersRoute = AdminAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppQrRoute = AdminAppQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminMenuTableRoute = AdminMenuTableRouteImport.update({
  id: '/admin/menu/$table',
  path: '/admin/menu/$table',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenAppKdsRoute = KitchenAppKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => KitchenAppRoute,
} as any)
const ReceptionAppCustomersRoute = ReceptionAppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ReceptionAppRoute,
} as any)
const ReceptionAppDashboardRoute = ReceptionAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ReceptionAppRoute,
} as any)
const ReceptionAppProfileRoute = ReceptionAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ReceptionAppRoute,
} as any)
const AdminAppBillingInvoicesRoute = AdminAppBillingInvoicesRouteImport.update({
  id: '/billing/invoices',
  path: '/billing/invoices',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppBillingPaymentsRoute = AdminAppBillingPaymentsRouteImport.update({
  id: '/billing/payments',
  path: '/billing/payments',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppInventoryIngredientsRoute =
  AdminAppInventoryIngredientsRouteImport.update({
    id: '/inventory/ingredients',
    path: '/inventory/ingredients',
    getParentRoute: () => AdminAppRoute,
  } as any)
const AdminAppInventoryPurchaseOrdersRoute =
  AdminAppInventoryPurchaseOrdersRouteImport.update({
    id: '/inventory/purchase-orders',
    path: '/inventory/purchase-orders',
    getParentRoute: () => AdminAppRoute,
  } as any)
const AdminAppInventorySuppliersRoute =
  AdminAppInventorySuppliersRouteImport.update({
    id: '/inventory/suppliers',
    path: '/inventory/suppliers',
    getParentRoute: () => AdminAppRoute,
  } as any)
const AdminAppMenuItemsRoute = AdminAppMenuItemsRouteImport.update({
  id: '/menu/items',
  path: '/menu/items',
  getParentRoute: () => AdminAppRoute,
} as any)
const KitchenAppMenuAddRoute = KitchenAppMenuAddRouteImport.update({
  id: '/menu/add',
  path: '/menu/add',
  getParentRoute: () => KitchenAppRoute,
} as any)
const KitchenAppMenuItemsRoute = KitchenAppMenuItemsRouteImport.update({
  id: '/menu/items',
  path: '/menu/items',
  getParentRoute: () => KitchenAppRoute,
} as any)
const KitchenAppOrdersHistoryRoute = KitchenAppOrdersHistoryRouteImport.update({
  id: '/orders/history',
  path: '/orders/history',
  getParentRoute: () => KitchenAppRoute,
} as any)
const KitchenAppOrdersLiveRoute = KitchenAppOrdersLiveRouteImport.update({
  id: '/orders/live',
  path: '/orders/live',
  getParentRoute: () => KitchenAppRoute,
} as any)
const ReceptionAppBillingPaymentsRoute =
  ReceptionAppBillingPaymentsRouteImport.update({
    id: '/billing/payments',
    path: '/billing/payments',
    getParentRoute: () => ReceptionAppRoute,
  } as any)
const ReceptionAppInventoryIngredientsRoute =
  ReceptionAppInventoryIngredientsRouteImport.update({
    id: '/inventory/ingredients',
    path: '/inventory/ingredients',
    getParentRoute: () => ReceptionAppRoute,
  } as any)
const ReceptionAppInventoryPurchaseOrdersRoute =
  ReceptionAppInventoryPurchaseOrdersRouteImport.update({
    id: '/inventory/purchase-orders',
    path: '/inventory/purchase-orders',
    getParentRoute: () => ReceptionAppRoute,
  } as any)
const ReceptionAppInventorySuppliersRoute =
  ReceptionAppInventorySuppliersRouteImport.update({
    id: '/inventory/suppliers',
    path: '/inventory/suppliers',
    getParentRoute: () => ReceptionAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAppRouteWithChildren
  '/kitchen': typeof KitchenAppRouteWithChildren
  '/reception': typeof ReceptionAppRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/kitchen/': typeof KitchenIndexRoute
  '/reception/': typeof ReceptionIndexRoute
  '/admin/dashboard': typeof AdminAppDashboardRoute
  '/admin/employees': typeof AdminAppEmployeesRoute
  '/admin/kds': typeof AdminAppKdsRoute
  '/admin/orders': typeof AdminAppOrdersRoute
  '/admin/qr': typeof AdminAppQrRoute
  '/admin/menu/$table': typeof AdminMenuTableRoute
  '/kitchen/kds': typeof KitchenAppKdsRoute
  '/reception/customers': typeof ReceptionAppCustomersRoute
  '/reception/dashboard': typeof ReceptionAppDashboardRoute
  '/reception/profile': typeof ReceptionAppProfileRoute
  '/admin/billing/invoices': typeof AdminAppBillingInvoicesRoute
  '/admin/billing/payments': typeof AdminAppBillingPaymentsRoute
  '/admin/inventory/ingredients': typeof AdminAppInventoryIngredientsRoute
  '/admin/inventory/purchase-orders': typeof AdminAppInventoryPurchaseOrdersRoute
  '/admin/inventory/suppliers': typeof AdminAppInventorySuppliersRoute
  '/admin/menu/items': typeof AdminAppMenuItemsRoute
  '/kitchen/menu/add': typeof KitchenAppMenuAddRoute
  '/kitchen/menu/items': typeof KitchenAppMenuItemsRoute
  '/kitchen/orders/history': typeof KitchenAppOrdersHistoryRoute
  '/kitchen/orders/live': typeof KitchenAppOrdersLiveRoute
  '/reception/billing/payments': typeof ReceptionAppBillingPaymentsRoute
  '/reception/inventory/ingredients': typeof ReceptionAppInventoryIngredientsRoute
  '/reception/inventory/purchase-orders': typeof ReceptionAppInventoryPurchaseOrdersRoute
  '/reception/inventory/suppliers': typeof ReceptionAppInventorySuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/kitchen': typeof KitchenIndexRoute
  '/reception': typeof ReceptionIndexRoute
  '/admin/dashboard': typeof AdminAppDashboardRoute
  '/admin/employees': typeof AdminAppEmployeesRoute
  '/admin/kds': typeof AdminAppKdsRoute
  '/admin/orders': typeof AdminAppOrdersRoute
  '/admin/qr': typeof AdminAppQrRoute
  '/admin/menu/$table': typeof AdminMenuTableRoute
  '/kitchen/kds': typeof KitchenAppKdsRoute
  '/reception/customers': typeof ReceptionAppCustomersRoute
  '/reception/dashboard': typeof ReceptionAppDashboardRoute
  '/reception/profile': typeof ReceptionAppProfileRoute
  '/admin/billing/invoices': typeof AdminAppBillingInvoicesRoute
  '/admin/billing/payments': typeof AdminAppBillingPaymentsRoute
  '/admin/inventory/ingredients': typeof AdminAppInventoryIngredientsRoute
  '/admin/inventory/purchase-orders': typeof AdminAppInventoryPurchaseOrdersRoute
  '/admin/inventory/suppliers': typeof AdminAppInventorySuppliersRoute
  '/admin/menu/items': typeof AdminAppMenuItemsRoute
  '/kitchen/menu/add': typeof KitchenAppMenuAddRoute
  '/kitchen/menu/items': typeof KitchenAppMenuItemsRoute
  '/kitchen/orders/history': typeof KitchenAppOrdersHistoryRoute
  '/kitchen/orders/live': typeof KitchenAppOrdersLiveRoute
  '/reception/billing/payments': typeof ReceptionAppBillingPaymentsRoute
  '/reception/inventory/ingredients': typeof ReceptionAppInventoryIngredientsRoute
  '/reception/inventory/purchase-orders': typeof ReceptionAppInventoryPurchaseOrdersRoute
  '/reception/inventory/suppliers': typeof ReceptionAppInventorySuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_app': typeof AdminAppRouteWithChildren
  '/kitchen/_app': typeof KitchenAppRouteWithChildren
  '/reception/_app': typeof ReceptionAppRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/kitchen/': typeof KitchenIndexRoute
  '/reception/': typeof ReceptionIndexRoute
  '/admin/_app/dashboard': typeof AdminAppDashboardRoute
  '/admin/_app/employees': typeof AdminAppEmployeesRoute
  '/admin/_app/kds': typeof AdminAppKdsRoute
  '/admin/_app/orders': typeof AdminAppOrdersRoute
  '/admin/_app/qr': typeof AdminAppQrRoute
  '/admin/menu/$table': typeof AdminMenuTableRoute
  '/kitchen/_app/kds': typeof KitchenAppKdsRoute
  '/reception/_app/customers': typeof ReceptionAppCustomersRoute
  '/reception/_app/dashboard': typeof ReceptionAppDashboardRoute
  '/reception/_app/profile': typeof ReceptionAppProfileRoute
  '/admin/_app/billing/invoices': typeof AdminAppBillingInvoicesRoute
  '/admin/_app/billing/payments': typeof AdminAppBillingPaymentsRoute
  '/admin/_app/inventory/ingredients': typeof AdminAppInventoryIngredientsRoute
  '/admin/_app/inventory/purchase-orders': typeof AdminAppInventoryPurchaseOrdersRoute
  '/admin/_app/inventory/suppliers': typeof AdminAppInventorySuppliersRoute
  '/admin/_app/menu/items': typeof AdminAppMenuItemsRoute
  '/kitchen/_app/menu/add': typeof KitchenAppMenuAddRoute
  '/kitchen/_app/menu/items': typeof KitchenAppMenuItemsRoute
  '/kitchen/_app/orders/history': typeof KitchenAppOrdersHistoryRoute
  '/kitchen/_app/orders/live': typeof KitchenAppOrdersLiveRoute
  '/reception/_app/billing/payments': typeof ReceptionAppBillingPaymentsRoute
  '/reception/_app/inventory/ingredients': typeof ReceptionAppInventoryIngredientsRoute
  '/reception/_app/inventory/purchase-orders': typeof ReceptionAppInventoryPurchaseOrdersRoute
  '/reception/_app/inventory/suppliers': typeof ReceptionAppInventorySuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kitchen'
    | '/reception'
    | '/admin/'
    | '/kitchen/'
    | '/reception/'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/kds'
    | '/admin/orders'
    | '/admin/qr'
    | '/admin/menu/$table'
    | '/kitchen/kds'
    | '/reception/customers'
    | '/reception/dashboard'
    | '/reception/profile'
    | '/admin/billing/invoices'
    | '/admin/billing/payments'
    | '/admin/inventory/ingredients'
    | '/admin/inventory/purchase-orders'
    | '/admin/inventory/suppliers'
    | '/admin/menu/items'
    | '/kitchen/menu/add'
    | '/kitchen/menu/items'
    | '/kitchen/orders/history'
    | '/kitchen/orders/live'
    | '/reception/billing/payments'
    | '/reception/inventory/ingredients'
    | '/reception/inventory/purchase-orders'
    | '/reception/inventory/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/kitchen'
    | '/reception'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/kds'
    | '/admin/orders'
    | '/admin/qr'
    | '/admin/menu/$table'
    | '/kitchen/kds'
    | '/reception/customers'
    | '/reception/dashboard'
    | '/reception/profile'
    | '/admin/billing/invoices'
    | '/admin/billing/payments'
    | '/admin/inventory/ingredients'
    | '/admin/inventory/purchase-orders'
    | '/admin/inventory/suppliers'
    | '/admin/menu/items'
    | '/kitchen/menu/add'
    | '/kitchen/menu/items'
    | '/kitchen/orders/history'
    | '/kitchen/orders/live'
    | '/reception/billing/payments'
    | '/reception/inventory/ingredients'
    | '/reception/inventory/purchase-orders'
    | '/reception/inventory/suppliers'
  id:
    | '__root__'
    | '/'
    | '/admin/_app'
    | '/kitchen/_app'
    | '/reception/_app'
    | '/admin/'
    | '/kitchen/'
    | '/reception/'
    | '/admin/_app/dashboard'
    | '/admin/_app/employees'
    | '/admin/_app/kds'
    | '/admin/_app/orders'
    | '/admin/_app/qr'
    | '/admin/menu/$table'
    | '/kitchen/_app/kds'
    | '/reception/_app/customers'
    | '/reception/_app/dashboard'
    | '/reception/_app/profile'
    | '/admin/_app/billing/invoices'
    | '/admin/_app/billing/payments'
    | '/admin/_app/inventory/ingredients'
    | '/admin/_app/inventory/purchase-orders'
    | '/admin/_app/inventory/suppliers'
    | '/admin/_app/menu/items'
    | '/kitchen/_app/menu/add'
    | '/kitchen/_app/menu/items'
    | '/kitchen/_app/orders/history'
    | '/kitchen/_app/orders/live'
    | '/reception/_app/billing/payments'
    | '/reception/_app/inventory/ingredients'
    | '/reception/_app/inventory/purchase-orders'
    | '/reception/_app/inventory/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAppRoute: typeof AdminAppRouteWithChildren
  KitchenAppRoute: typeof KitchenAppRouteWithChildren
  ReceptionAppRoute: typeof ReceptionAppRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  KitchenIndexRoute: typeof KitchenIndexRoute
  ReceptionIndexRoute: typeof ReceptionIndexRoute
  AdminMenuTableRoute: typeof AdminMenuTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_app': {
      id: '/admin/_app'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen/': {
      id: '/kitchen/'
      path: '/kitchen'
      fullPath: '/kitchen/'
      preLoaderRoute: typeof KitchenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen/_app': {
      id: '/kitchen/_app'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/': {
      id: '/reception/'
      path: '/reception'
      fullPath: '/reception/'
      preLoaderRoute: typeof ReceptionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/_app': {
      id: '/reception/_app'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_app/dashboard': {
      id: '/admin/_app/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAppDashboardRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/employees': {
      id: '/admin/_app/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminAppEmployeesRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/kds': {
      id: '/admin/_app/kds'
      path: '/kds'
      fullPath: '/admin/kds'
      preLoaderRoute: typeof AdminAppKdsRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/orders': {
      id: '/admin/_app/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAppOrdersRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/qr': {
      id: '/admin/_app/qr'
      path: '/qr'
      fullPath: '/admin/qr'
      preLoaderRoute: typeof AdminAppQrRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/menu/$table': {
      id: '/admin/menu/$table'
      path: '/admin/menu/$table'
      fullPath: '/admin/menu/$table'
      preLoaderRoute: typeof AdminMenuTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen/_app/kds': {
      id: '/kitchen/_app/kds'
      path: '/kds'
      fullPath: '/kitchen/kds'
      preLoaderRoute: typeof KitchenAppKdsRouteImport
      parentRoute: typeof KitchenAppRoute
    }
    '/reception/_app/customers': {
      id: '/reception/_app/customers'
      path: '/customers'
      fullPath: '/reception/customers'
      preLoaderRoute: typeof ReceptionAppCustomersRouteImport
      parentRoute: typeof ReceptionAppRoute
    }
    '/reception/_app/dashboard': {
      id: '/reception/_app/dashboard'
      path: '/dashboard'
      fullPath: '/reception/dashboard'
      preLoaderRoute: typeof ReceptionAppDashboardRouteImport
      parentRoute: typeof ReceptionAppRoute
    }
    '/reception/_app/profile': {
      id: '/reception/_app/profile'
      path: '/profile'
      fullPath: '/reception/profile'
      preLoaderRoute: typeof ReceptionAppProfileRouteImport
      parentRoute: typeof ReceptionAppRoute
    }
    '/admin/_app/billing/invoices': {
      id: '/admin/_app/billing/invoices'
      path: '/billing/invoices'
      fullPath: '/admin/billing/invoices'
      preLoaderRoute: typeof AdminAppBillingInvoicesRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/billing/payments': {
      id: '/admin/_app/billing/payments'
      path: '/billing/payments'
      fullPath: '/admin/billing/payments'
      preLoaderRoute: typeof AdminAppBillingPaymentsRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/inventory/ingredients': {
      id: '/admin/_app/inventory/ingredients'
      path: '/inventory/ingredients'
      fullPath: '/admin/inventory/ingredients'
      preLoaderRoute: typeof AdminAppInventoryIngredientsRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/inventory/purchase-orders': {
      id: '/admin/_app/inventory/purchase-orders'
      path: '/inventory/purchase-orders'
      fullPath: '/admin/inventory/purchase-orders'
      preLoaderRoute: typeof AdminAppInventoryPurchaseOrdersRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/inventory/suppliers': {
      id: '/admin/_app/inventory/suppliers'
      path: '/inventory/suppliers'
      fullPath: '/admin/inventory/suppliers'
      preLoaderRoute: typeof AdminAppInventorySuppliersRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/menu/items': {
      id: '/admin/_app/menu/items'
      path: '/menu/items'
      fullPath: '/admin/menu/items'
      preLoaderRoute: typeof AdminAppMenuItemsRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/kitchen/_app/menu/add': {
      id: '/kitchen/_app/menu/add'
      path: '/menu/add'
      fullPath: '/kitchen/menu/add'
      preLoaderRoute: typeof KitchenAppMenuAddRouteImport
      parentRoute: typeof KitchenAppRoute
    }
    '/kitchen/_app/menu/items': {
      id: '/kitchen/_app/menu/items'
      path: '/menu/items'
      fullPath: '/kitchen/menu/items'
      preLoaderRoute: typeof KitchenAppMenuItemsRouteImport
      parentRoute: typeof KitchenAppRoute
    }
    '/kitchen/_app/orders/history': {
      id: '/kitchen/_app/orders/history'
      path: '/orders/history'
      fullPath: '/kitchen/orders/history'
      preLoaderRoute: typeof KitchenAppOrdersHistoryRouteImport
      parentRoute: typeof KitchenAppRoute
    }
    '/kitchen/_app/orders/live': {
      id: '/kitchen/_app/orders/live'
      path: '/orders/live'
      fullPath: '/kitchen/orders/live'
      preLoaderRoute: typeof KitchenAppOrdersLiveRouteImport
      parentRoute: typeof KitchenAppRoute
    }
    '/reception/_app/billing/payments': {
      id: '/reception/_app/billing/payments'
      path: '/billing/payments'
      fullPath: '/reception/billing/payments'
      preLoaderRoute: typeof ReceptionAppBillingPaymentsRouteImport
      parentRoute: typeof ReceptionAppRoute
    }
    '/reception/_app/inventory/ingredients': {
      id: '/reception/_app/inventory/ingredients'
      path: '/inventory/ingredients'
      fullPath: '/reception/inventory/ingredients'
      preLoaderRoute: typeof ReceptionAppInventoryIngredientsRouteImport
      parentRoute: typeof ReceptionAppRoute
    }
    '/reception/_app/inventory/purchase-orders': {
      id: '/reception/_app/inventory/purchase-orders'
      path: '/inventory/purchase-orders'
      fullPath: '/reception/inventory/purchase-orders'
      preLoaderRoute: typeof ReceptionAppInventoryPurchaseOrdersRouteImport
      parentRoute: typeof ReceptionAppRoute
    }
    '/reception/_app/inventory/suppliers': {
      id: '/reception/_app/inventory/suppliers'
      path: '/inventory/suppliers'
      fullPath: '/reception/inventory/suppliers'
      preLoaderRoute: typeof ReceptionAppInventorySuppliersRouteImport
      parentRoute: typeof ReceptionAppRoute
    }
  }
}

interface AdminAppRouteChildren {
  AdminAppDashboardRoute: typeof AdminAppDashboardRoute
  AdminAppEmployeesRoute: typeof AdminAppEmployeesRoute
  AdminAppKdsRoute: typeof AdminAppKdsRoute
  AdminAppOrdersRoute: typeof AdminAppOrdersRoute
  AdminAppQrRoute: typeof AdminAppQrRoute
  AdminAppBillingInvoicesRoute: typeof AdminAppBillingInvoicesRoute
  AdminAppBillingPaymentsRoute: typeof AdminAppBillingPaymentsRoute
  AdminAppInventoryIngredientsRoute: typeof AdminAppInventoryIngredientsRoute
  AdminAppInventoryPurchaseOrdersRoute: typeof AdminAppInventoryPurchaseOrdersRoute
  AdminAppInventorySuppliersRoute: typeof AdminAppInventorySuppliersRoute
  AdminAppMenuItemsRoute: typeof AdminAppMenuItemsRoute
}

const AdminAppRouteChildren: AdminAppRouteChildren = {
  AdminAppDashboardRoute: AdminAppDashboardRoute,
  AdminAppEmployeesRoute: AdminAppEmployeesRoute,
  AdminAppKdsRoute: AdminAppKdsRoute,
  AdminAppOrdersRoute: AdminAppOrdersRoute,
  AdminAppQrRoute: AdminAppQrRoute,
  AdminAppBillingInvoicesRoute: AdminAppBillingInvoicesRoute,
  AdminAppBillingPaymentsRoute: AdminAppBillingPaymentsRoute,
  AdminAppInventoryIngredientsRoute: AdminAppInventoryIngredientsRoute,
  AdminAppInventoryPurchaseOrdersRoute: AdminAppInventoryPurchaseOrdersRoute,
  AdminAppInventorySuppliersRoute: AdminAppInventorySuppliersRoute,
  AdminAppMenuItemsRoute: AdminAppMenuItemsRoute,
}

const AdminAppRouteWithChildren = AdminAppRoute._addFileChildren(
  AdminAppRouteChildren,
)

interface KitchenAppRouteChildren {
  KitchenAppKdsRoute: typeof KitchenAppKdsRoute
  KitchenAppMenuAddRoute: typeof KitchenAppMenuAddRoute
  KitchenAppMenuItemsRoute: typeof KitchenAppMenuItemsRoute
  KitchenAppOrdersHistoryRoute: typeof KitchenAppOrdersHistoryRoute
  KitchenAppOrdersLiveRoute: typeof KitchenAppOrdersLiveRoute
}

const KitchenAppRouteChildren: KitchenAppRouteChildren = {
  KitchenAppKdsRoute: KitchenAppKdsRoute,
  KitchenAppMenuAddRoute: KitchenAppMenuAddRoute,
  KitchenAppMenuItemsRoute: KitchenAppMenuItemsRoute,
  KitchenAppOrdersHistoryRoute: KitchenAppOrdersHistoryRoute,
  KitchenAppOrdersLiveRoute: KitchenAppOrdersLiveRoute,
}

const KitchenAppRouteWithChildren = KitchenAppRoute._addFileChildren(
  KitchenAppRouteChildren,
)

interface ReceptionAppRouteChildren {
  ReceptionAppCustomersRoute: typeof ReceptionAppCustomersRoute
  ReceptionAppDashboardRoute: typeof ReceptionAppDashboardRoute
  ReceptionAppProfileRoute: typeof ReceptionAppProfileRoute
  ReceptionAppBillingPaymentsRoute: typeof ReceptionAppBillingPaymentsRoute
  ReceptionAppInventoryIngredientsRoute: typeof ReceptionAppInventoryIngredientsRoute
  ReceptionAppInventoryPurchaseOrdersRoute: typeof ReceptionAppInventoryPurchaseOrdersRoute
  ReceptionAppInventorySuppliersRoute: typeof ReceptionAppInventorySuppliersRoute
}

const ReceptionAppRouteChildren: ReceptionAppRouteChildren = {
  ReceptionAppCustomersRoute: ReceptionAppCustomersRoute,
  ReceptionAppDashboardRoute: ReceptionAppDashboardRoute,
  ReceptionAppProfileRoute: ReceptionAppProfileRoute,
  ReceptionAppBillingPaymentsRoute: ReceptionAppBillingPaymentsRoute,
  ReceptionAppInventoryIngredientsRoute: ReceptionAppInventoryIngredientsRoute,
  ReceptionAppInventoryPurchaseOrdersRoute:
    ReceptionAppInventoryPurchaseOrdersRoute,
  ReceptionAppInventorySuppliersRoute: ReceptionAppInventorySuppliersRoute,
}

const ReceptionAppRouteWithChildren = ReceptionAppRoute._addFileChildren(
  ReceptionAppRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAppRoute: AdminAppRouteWithChildren,
  KitchenAppRoute: KitchenAppRouteWithChildren,
  ReceptionAppRoute: ReceptionAppRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  KitchenIndexRoute: KitchenIndexRoute,
  ReceptionIndexRoute: ReceptionIndexRoute,
  AdminMenuTableRoute: AdminMenuTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
